language: php

php:
  - 5.3
  - 5.4

before_install:
  - mkdir ../libraries
  - git clone --branch=master --depth=100 --quiet git://github.com/UnionOfRAD/lithium.git ../libraries/lithium
  - composer self-update
  - composer install --prefer-source --dev
  - sed -i '$d' config/bootstrap.php
  - echo "use lithium\core\Libraries;" >> config/bootstrap.php
  - echo "Libraries::add('li3_quality');" >> config/bootstrap.php
  - echo "Libraries::add('swiftmailer', array('prefix' => 'Swift_', 'path' => 'vendor/swiftmailer/swiftmailer', 'bootstrap' => 'lib/swift_required.php'));" >> config/bootstrap.php

script: ../libraries/lithium/console/li3 test tests && ../libraries/lithium/console/li3 quality syntax --library=li3_mailer
